# Generated by Django 5.2.6 on 2025-10-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cat_nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cat_descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id_contacto', models.FloatField(primary_key=True, serialize=False)),
                ('tipo_contacto', models.CharField(blank=True, max_length=1, null=True)),
                ('dato_contacto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'contactos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadopedidos',
            fields=[
                ('est_id', models.IntegerField(primary_key=True, serialize=False)),
                ('est_nombre', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
            options={
                'db_table': 'estadopedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadousuarios',
            fields=[
                ('id_estado_usuario', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'estadousuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('ped_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ped_fecha_pedido', models.DateField(blank=True, null=True)),
                ('ped_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ped_direccion_envio', models.CharField(blank=True, max_length=200, null=True)),
                ('ped_notas', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidosProductos',
            fields=[
                ('pk', models.CompositePrimaryKey('ped_id', 'prod_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('pped_cantidad', models.IntegerField(blank=True, null=True)),
                ('pped_precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'pedidos_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_perfil', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'perfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfilpermisos',
            fields=[
                ('id_perfil_permiso', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'perfilpermisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descripcion_permiso', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('prod_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prod_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('prod_precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prod_stock', models.IntegerField(blank=True, null=True)),
                ('prod_imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('prod_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('au_type', models.IntegerField(blank=True, null=True)),
                ('auditoria', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'productos_auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rolperfiles',
            fields=[
                ('id_rol_perfil', models.FloatField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rolperfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexos',
            fields=[
                ('id_sexo', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_sexo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sexos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.FloatField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
