# Generated by Django 5.2.6 on 2026-04-25 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cat_nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cat_descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Config_Contacto',
            fields=[
                ('id_regla', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('regex_val', models.CharField(blank=True, max_length=200, null=True)),
                ('min_length', models.FloatField(blank=True, null=True)),
                ('max_length', models.FloatField(blank=True, null=True)),
                ('mensaje_error', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'config_contacto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consultas_Dinamicas',
            fields=[
                ('cons_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cons_nombre', models.CharField(max_length=50, unique=True)),
                ('cons_sql', models.CharField(max_length=4000)),
                ('cons_descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'consultas_dinamicas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedidos',
            fields=[
                ('est_id', models.IntegerField(primary_key=True, serialize=False)),
                ('est_nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estadopedidos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('ped_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ped_fecha_pedido', models.DateField(blank=True, null=True)),
                ('ped_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('ped_estado', models.FloatField(blank=True, default=1, max_length=1, null=True)),
                ('ped_direccion_envio', models.CharField(blank=True, max_length=200, null=True)),
                ('ped_notas', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'pedidos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id_perfil', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'perfiles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos_Auditoria',
            fields=[
                ('dummy_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('au_type', models.IntegerField(blank=True, null=True)),
                ('auditoria', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'productos_auditoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sexos',
            fields=[
                ('id_sexo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sexo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sexos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_mod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mod', models.CharField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('url_mod', models.CharField(blank=True, max_length=200)),
                ('padre_mod', models.ForeignKey(blank=True, db_column='padre_mod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.modulos')),
            ],
            options={
                'db_table': 'modulos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfilpermisos',
            fields=[
                ('pk', models.CompositePrimaryKey('perfil_id', 'mod_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('can_create', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('can_read', models.CharField(blank=True, default='Y', max_length=1, null=True)),
                ('can_update', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('can_delete', models.CharField(blank=True, default='N', max_length=1, null=True)),
                ('mod_id', models.ForeignKey(db_column='mod_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.modulos')),
                ('perfil_id', models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.perfiles')),
            ],
            options={
                'db_table': 'perfilpermisos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('prod_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('prod_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_descripcion', models.CharField(blank=True, max_length=400, null=True)),
                ('prod_precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prod_stock', models.IntegerField(blank=True, null=True)),
                ('prod_imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('prod_descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.categoria')),
            ],
            options={
                'db_table': 'productos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PedidosProductos',
            fields=[
                ('pk', models.CompositePrimaryKey('ped_id', 'prod_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('pped_fecha_entrega', models.DateField(blank=True, null=True)),
                ('pped_cantidad', models.IntegerField(blank=True, null=True)),
                ('pped_precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pped_descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('pped_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('ped', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.pedidos')),
                ('pped_estado', models.ForeignKey(blank=True, db_column='pped_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.estadopedidos')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.productos')),
            ],
            options={
                'db_table': 'pedidos_productos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='perfiles',
            name='rol_id',
            field=models.ForeignKey(blank=True, db_column='rol_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.roles'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('primer_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.FloatField(blank=True, default=1, max_length=1, null=True)),
                ('usuario_id_perfil', models.ForeignKey(db_column='usuario_id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.perfiles')),
                ('usuario_id_sexo', models.ForeignKey(db_column='usuario_id_sexo', on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.sexos')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pedidos',
            name='usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.usuarios'),
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id_contacto', models.IntegerField(primary_key=True, serialize=False)),
                ('dato_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_contacto', models.ForeignKey(blank=True, db_column='tipo_contacto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.config_contacto')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.usuarios')),
            ],
            options={
                'db_table': 'contactos',
                'managed': True,
            },
        ),
    ]
