# Generated by Django 5.2.6 on 2026-04-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='prod_nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
