# Generated by Django 5.2.6 on 2025-10-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estadousuarios',
        ),
    ]
