# Generated by Django 5.2.6 on 2025-10-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0002_delete_estadousuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estadopedidos',
        ),
    ]
