# Generated by Django 5.2.6 on 2026-05-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0002_alter_productos_prod_nombre'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contactos',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'tipo_contacto'), name='uq_usuario_tipo_contacto'),
        ),
        migrations.AddConstraint(
            model_name='pedidos',
            constraint=models.CheckConstraint(condition=models.Q(('ped_total__gte', 0)), name='ck_total_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.CheckConstraint(condition=models.Q(('prod_precio_venta__gt', 0)), name='ck_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.CheckConstraint(condition=models.Q(('prod_stock__gte', 0)), name='ck_stock_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='productos',
            constraint=models.CheckConstraint(condition=models.Q(('prod_descuento__lte', 99)), name='ck_descuento_maximo'),
        ),
        migrations.AddConstraint(
            model_name='usuarios',
            constraint=models.CheckConstraint(condition=models.Q(('activo', 0), ('activo', 1), _connector='OR'), name='ck_activo_valido'),
        ),
    ]
