# Generated by Django 5.2.6 on 2025-11-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0003_delete_estadopedidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedidos',
            fields=[
                ('est_id', models.FloatField(primary_key=True, serialize=False)),
                ('ets_nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estado_pedidos',
                'managed': False,
            },
        ),
    ]
