# Generated by Django 5.2.6 on 2026-05-06 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0003_contactos_uq_usuario_tipo_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='ped_estado',
            field=models.ForeignKey(db_column='ped_estado', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos', to='MultiverseAnimeStore.estadopedidos'),
        ),
    ]
