# Generated by Django 5.2.6 on 2025-11-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0004_estadopedidos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estadopedidos',
            table='estadopedidos',
        ),
    ]
