# Generated by Django 5.2.6 on 2026-05-18 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0005_productos_auditoria_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='prod_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='cat_descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='cat_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='cat_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='config_contacto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='config_contacto',
            name='id_regla',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='config_contacto',
            name='max_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud máxima'),
        ),
        migrations.AlterField(
            model_name='config_contacto',
            name='mensaje_error',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mensaje de error'),
        ),
        migrations.AlterField(
            model_name='config_contacto',
            name='min_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud mínima'),
        ),
        migrations.AlterField(
            model_name='config_contacto',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='config_contacto',
            name='regex_val',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Regex'),
        ),
        migrations.AlterField(
            model_name='consultas_dinamicas',
            name='cons_descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='consultas_dinamicas',
            name='cons_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='consultas_dinamicas',
            name='cons_nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='consultas_dinamicas',
            name='cons_sql',
            field=models.CharField(max_length=4000, verbose_name='Consulta SQL'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='dato_contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='id_contacto',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.usuarios', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='tipo_contacto',
            field=models.ForeignKey(blank=True, db_column='tipo_contacto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.config_contacto', verbose_name='Tipo de contacto'),
        ),
        migrations.AlterField(
            model_name='estadopedidos',
            name='est_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estadopedidos',
            name='est_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='id_mod',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='nombre_mod',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='padre_mod',
            field=models.ForeignKey(blank=True, db_column='padre_mod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.modulos', verbose_name='Módulo padre'),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='url_mod',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_direccion_envio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección de envío'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_estado',
            field=models.ForeignKey(db_column='ped_estado', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos', to='MultiverseAnimeStore.estadopedidos', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_fecha_pedido',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pedido'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_notas',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ped_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='usu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.usuarios', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pedidosproductos',
            name='ped',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.pedidos', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='pedidosproductos',
            name='pped_cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='pedidosproductos',
            name='pped_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='pedidosproductos',
            name='pped_estado',
            field=models.ForeignKey(blank=True, db_column='pped_estado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.estadopedidos', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedidosproductos',
            name='pped_fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='pedidosproductos',
            name='pped_precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='pedidosproductos',
            name='pped_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedidosproductos',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.productos', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='id_perfil',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='rol_id',
            field=models.ForeignKey(blank=True, db_column='rol_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.roles', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='perfilpermisos',
            name='can_create',
            field=models.CharField(blank=True, default='N', max_length=1, null=True, verbose_name='Crear'),
        ),
        migrations.AlterField(
            model_name='perfilpermisos',
            name='can_delete',
            field=models.CharField(blank=True, default='N', max_length=1, null=True, verbose_name='Eliminar'),
        ),
        migrations.AlterField(
            model_name='perfilpermisos',
            name='can_read',
            field=models.CharField(blank=True, default='Y', max_length=1, null=True, verbose_name='Leer'),
        ),
        migrations.AlterField(
            model_name='perfilpermisos',
            name='can_update',
            field=models.CharField(blank=True, default='N', max_length=1, null=True, verbose_name='Actualizar'),
        ),
        migrations.AlterField(
            model_name='perfilpermisos',
            name='mod_id',
            field=models.ForeignKey(db_column='mod_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.modulos', verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='perfilpermisos',
            name='perfil_id',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.perfiles', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_descripcion',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_imagen_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL de imagen'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_nombre',
            field=models.CharField(default='Sin nombre', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de venta'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='prod_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='productos_auditoria',
            name='dummy_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='id_rol',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sexos',
            name='id_sexo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sexos',
            name='nombre_sexo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='activo',
            field=models.FloatField(blank=True, default=1, max_length=1, null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_usuario',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario_id_perfil',
            field=models.ForeignKey(db_column='usuario_id_perfil', on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.perfiles', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario_id_sexo',
            field=models.ForeignKey(db_column='usuario_id_sexo', on_delete=django.db.models.deletion.DO_NOTHING, to='MultiverseAnimeStore.sexos', verbose_name='Sexo'),
        ),
    ]
