# Generated by Django 5.2.6 on 2025-11-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0005_alter_estadopedidos_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Contactos',
            fields=[
                ('id_regla', models.FloatField(primary_key=True, serialize=False)),
                ('tipo_contacto', models.CharField(blank=True, max_length=1, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('regex_val', models.CharField(blank=True, max_length=200, null=True)),
                ('min_length', models.FloatField(blank=True, null=True)),
                ('max_length', models.FloatField(blank=True, null=True)),
                ('mensaje_error', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'config_contactos',
                'managed': False,
            },
        ),
    ]
