# Generated by Django 5.2.6 on 2026-05-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0006_productos_prod_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Clave')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor')),
            ],
            options={
                'db_table': 'configuracion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='prod_destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado en inicio'),
        ),
    ]
