# Generated by Django 5.2.6 on 2025-11-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0006_config_contactos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config_Contacto',
            fields=[
                ('id_regla', models.FloatField(primary_key=True, serialize=False)),
                ('nombre_contacto', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('regex_val', models.CharField(blank=True, max_length=200, null=True)),
                ('min_length', models.FloatField(blank=True, null=True)),
                ('max_length', models.FloatField(blank=True, null=True)),
                ('mensaje_error', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'config_contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id_mod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mod', models.CharField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('url_mod', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos_Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('au_type', models.IntegerField(blank=True, null=True)),
                ('auditoria', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'productos_auditoria',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Config_Contactos',
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
        migrations.DeleteModel(
            name='ProductosAuditoria',
        ),
        migrations.DeleteModel(
            name='Rolperfiles',
        ),
    ]
