# Generated by Django 5.2.6 on 2025-11-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiverseAnimeStore', '0007_config_contacto_modulos_productos_auditoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas_Dinamicas',
            fields=[
                ('cons_id', models.FloatField(primary_key=True, serialize=False)),
                ('cons_nombre', models.CharField(max_length=50, unique=True)),
                ('cons_sql', models.CharField(max_length=4000)),
                ('cons_descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'consultas_dinamicas',
                'managed': False,
            },
        ),
    ]
