from django.urls import path
from .views import (
    CategoriaListView,
    CategoriaDetailView,
    CategoriaCreateView,
    CategoriaUpdateView,
    CategoriaDeleteView,
    ContactosListView,
    ContactosDetailView,
    ContactosCreateView,
    ContactosUpdateView,
    ContactosDeleteView,
    PedidosListView,
    PedidosDetailView,
    PedidosCreateView,
    PedidosUpdateView,
    PedidosDeleteView,
    ProductosListView,
    ProductosDetailView,
    ProductosCreateView,
    ProductosUpdateView,
    ProductosDeleteView,
    UsuariosListView,
    UsuariosDetailView,
    UsuariosCreateView,
    UsuariosUpdateView,
    UsuariosDeleteView,
    RolesListView,
    RolesDetailView,
    RolesCreateView,
    RolesUpdateView,
    RolesDeleteView,
    PerfilesListView,
    PerfilesDetailView,
    PerfilesCreateView,
    PerfilesUpdateView,
    PerfilesDeleteView,
    SexosListView,
    SexosDetailView,
    SexosCreateView,
    SexosUpdateView,
    SexosDeleteView,
    EstadoPedidosListView,
    EstadoPedidosDetailView,
    EstadoPedidosCreateView,
    EstadoPedidosUpdateView,
    EstadoPedidosDeleteView,
    ConfigContactoListView,
    ConfigContactoDetailView,
    ConfigContactoCreateView,
    ConfigContactoUpdateView,
    ConfigContactoDeleteView,
    PedidoProductoUpdateFormView,
    ProductosAuditoriaView,
    ConsultasDinamicasCreateView,
    ConsultasDinamicasDeleteView,
    ConsultasDinamicasDetailView,
    ConsultasDinamicasListView,
    ConsultasDinamicasUpdateView,
    reporte_view,
    logout_view,
    login_view,
    register_view
)

urlpatterns = [

    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),


    path('categorias/', CategoriaListView.as_view(), name='categoria_list'),
    path('categorias/<str:pk>/detalle/', CategoriaDetailView.as_view(), name='categoria_detail'),
    path('categorias/crear/', CategoriaCreateView, name='categoria_create'),
    path('categorias/<str:pk>/editar/', CategoriaUpdateView, name='categoria_update'),
    path('categorias/<str:pk>/eliminar/', CategoriaDeleteView.as_view(), name='categoria_delete'),

    path('contactos/', ContactosListView.as_view(), name='contactos_list'),
    path('contactos/<int:pk>/', ContactosDetailView.as_view(), name='contactos_detail'),
    path('contactos/crear/', ContactosCreateView, name='contactos_create'),
    path('contactos/<int:pk>/editar/', ContactosUpdateView, name='contactos_update'),
    path('contactos/<int:pk>/eliminar/', ContactosDeleteView, name='contactos_delete'),

    path('pedidos/', PedidosListView.as_view(), name='pedidos_list'),
    path('pedidos/<int:pk>/', PedidosDetailView.as_view(), name='pedidos_detail'),
    path('pedidos/crear/', PedidosCreateView, name='pedidos_create'),
    path('pedidos/<int:pk>/editar/', PedidosUpdateView, name='pedidos_update'),
    path('pedidos/<int:pk>/eliminar/', PedidosDeleteView, name='pedidos_delete'),

    path('productos/', ProductosListView.as_view(), name='productos_list'),
    path('productos/<str:pk>/detalle/', ProductosDetailView.as_view(), name='productos_detail'),
    path('productos/crear/', ProductosCreateView, name='productos_create'),
    path('productos/<str:pk>/editar/', ProductosUpdateView, name='productos_update'),
    path('productos/<str:pk>/eliminar/', ProductosDeleteView.as_view(), name='productos_delete'),
    
    path('productos_auditoria/', ProductosAuditoriaView, name='productos_auditoria'),

    path('usuarios/', UsuariosListView.as_view(), name='usuarios_list'),
    path('usuarios/<str:pk>/detalle/', UsuariosDetailView.as_view(), name='usuarios_detail'),
    path('usuarios/crear/', UsuariosCreateView, name='usuarios_create'),
    path('usuarios/<str:pk>/editar/', UsuariosUpdateView, name='usuarios_update'),
    path('usuarios/<str:pk>/eliminar/', UsuariosDeleteView, name='usuarios_delete'),


    path('roles/', RolesListView.as_view(), name='roles_list'),
    path('roles/<int:pk>/', RolesDetailView.as_view(), name='roles_detail'),
    path('roles/crear/', RolesCreateView, name='roles_create'),
    path('roles/<int:pk>/editar/', RolesUpdateView, name='roles_update'),
    path('roles/<int:pk>/eliminar/', RolesDeleteView.as_view(), name='roles_delete'),

    path('perfiles/', PerfilesListView.as_view(), name='perfiles_list'),
    path('perfiles/<int:pk>/', PerfilesDetailView.as_view(), name='perfiles_detail'),
    path('perfiles/crear/', PerfilesCreateView, name='perfiles_create'),
    path('perfiles/<int:pk>/editar/', PerfilesUpdateView, name='perfiles_update'),
    path('perfiles/<int:pk>/eliminar/', PerfilesDeleteView.as_view(), name='perfiles_delete'),

    path('sexos/', SexosListView.as_view(), name='sexos_list'),
    path('sexos/<int:pk>/', SexosDetailView.as_view(), name='sexos_detail'),
    path('sexos/crear/', SexosCreateView.as_view(), name='sexos_create'),
    path('sexos/<int:pk>/editar/', SexosUpdateView.as_view(), name='sexos_update'),
    path('sexos/<int:pk>/eliminar/', SexosDeleteView.as_view(), name='sexos_delete'),

    path('estado_pedidos/', EstadoPedidosListView.as_view(), name='estado_pedidos_list'),
    path('estado_pedidos/<int:pk>/', EstadoPedidosDetailView.as_view(), name='estado_pedidos_detail'),
    path('estado_pedidos/crear/', EstadoPedidosCreateView.as_view(), name='estado_pedidos_create'),
    path('estado_pedidos/<int:pk>/editar/', EstadoPedidosUpdateView.as_view(), name='estado_pedidos_update'),
    path('estado_pedidos/<int:pk>/eliminar/', EstadoPedidosDeleteView.as_view(), name='estado_pedidos_delete'),

    path('config_contacto/', ConfigContactoListView.as_view(), name='config_contacto_list'),
    path('config_contacto/<int:pk>/', ConfigContactoDetailView.as_view(), name='config_contacto_detail'),
    path('config_contacto/crear/', ConfigContactoCreateView, name='config_contacto_create'),
    path('config_contacto/<int:pk>/editar/', ConfigContactoUpdateView.as_view(), name='config_contacto_update'),
    path('config_contacto/<int:pk>/eliminar/', ConfigContactoDeleteView.as_view(), name='config_contacto_delete'),

    path('pedidos/<int:ped_id>/producto/<str:prod_id>/editar/', PedidoProductoUpdateFormView, name='pedido_producto_update'),


    path('consultas_dinamicas/', ConsultasDinamicasListView.as_view(), name='consultas_dinamicas_list'),
    path('consultas_dinamicas/<int:pk>/', ConsultasDinamicasDetailView.as_view(), name='consultas_dinamicas_detail'),
    path('consultas_dinamicas/crear/', ConsultasDinamicasCreateView, name='consultas_dinamicas_create'),
    path('consultas_dinamicas/<int:pk>/editar/', ConsultasDinamicasUpdateView.as_view(), name='consultas_dinamicas_update'),
    path('consultas_dinamicas/<int:pk>/eliminar/', ConsultasDinamicasDeleteView.as_view(), name='consultas_dinamicas_delete'),

    path('consultas_dinamicas/reporte/<int:id>/', reporte_view, name='consultas_dinamicas_reporte'),

]
