from django.urls import path
from .views import (
    CategoriaListView,
    CategoriaDetailView,
    CategoriaCreateView,
    CategoriaUpdateView,
    CategoriaDeleteView,
    ContactosListView,
    ContactosDetailView,
    ContactosCreateView,
    ContactosUpdateView,
    ContactosDeleteView,
    PedidosListView,
    PedidosDetailView,
    PedidosCreateView,
    PedidosUpdateView,
    PedidosDeleteView,
    ProductosListView,
    ProductosDetailView,
    ProductosCreateView,
    ProductosUpdateView,
    ProductosDeleteView,
    UsuariosListView,
    UsuariosDetailView,
    UsuariosCreateView,
    UsuariosUpdateView,
    UsuariosDeleteView,
    RolesListView,
    RolesDetailView,
    RolesCreateView,
    RolesUpdateView,
    RolesDeleteView,
)

urlpatterns = [
    path('categorias/', CategoriaListView.as_view(), name='categoria_list'),
    path('categorias/<int:pk>/', CategoriaDetailView.as_view(), name='categoria_detail'),
    path('categorias/crear/', CategoriaCreateView, name='categoria_create'),
    path('categorias/<int:pk>/editar/', CategoriaUpdateView, name='categoria_update'),
    path('categorias/<int:pk>/eliminar/', CategoriaDeleteView.as_view(), name='categoria_delete'),

    path('contactos/', ContactosListView.as_view(), name='contactos_list'),
    path('contactos/<int:pk>/', ContactosDetailView.as_view(), name='contactos_detail'),
    path('contactos/crear/', ContactosCreateView, name='contactos_create'),
    path('contactos/<int:pk>/editar/', ContactosUpdateView, name='contactos_update'),
    path('contactos/<int:pk>/eliminar/', ContactosDeleteView, name='contactos_delete'),

    path('pedidos/', PedidosListView.as_view(), name='pedidos_list'),
    path('pedidos/<int:pk>/', PedidosDetailView.as_view(), name='pedidos_detail'),
    path('pedidos/crear/', PedidosCreateView, name='pedidos_create'),
    path('pedidos/<int:pk>/editar/', PedidosUpdateView, name='pedidos_update'),
    path('pedidos/<int:pk>/eliminar/', PedidosDeleteView.as_view(), name='pedidos_delete'),

    path('productos/', ProductosListView.as_view(), name='productos_list'),
    path('productos/<int:pk>/', ProductosDetailView.as_view(), name='productos_detail'),
    path('productos/crear/', ProductosCreateView, name='productos_create'),
    path('productos/<int:pk>/editar/', ProductosUpdateView, name='productos_update'),
    path('productos/<int:pk>/eliminar/', ProductosDeleteView.as_view(), name='productos_delete'),

    path('usuarios/', UsuariosListView.as_view(), name='usuarios_list'),
    path('usuarios/<int:pk>/', UsuariosDetailView.as_view(), name='usuarios_detail'),
    path('usuarios/crear/', UsuariosCreateView, name='usuarios_create'),
    path('usuarios/<int:pk>/editar/', UsuariosUpdateView, name='usuarios_update'),
    path('usuarios/<int:pk>/eliminar/', UsuariosDeleteView.as_view(), name='usuarios_delete'),


    path('roles/', RolesListView.as_view(), name='roles_list'),
    path('roles/<int:pk>/', RolesDetailView.as_view(), name='roles_detail'),
    path('roles/crear/', RolesCreateView, name='roles_create'),
    path('roles/<int:pk>/editar/', RolesUpdateView, name='roles_update'),
    path('roles/<int:pk>/eliminar/', RolesDeleteView.as_view(), name='roles_delete'),
    
]
